resources:
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:d/demo-version
    branch: master
    private_key: {{demo_version_private_key}}
    password: " "
    file: v

- name: develop
  type: git
  source: &src
    uri: git@github.com:d/i-need-versions
    branch: develop
    private_key: {{i_need_versions_private_key}}
    password: " "

- name: master
  type: git
  source:
    <<: *src
    branch: master

jobs:
- name: test
  plan:
    - get: develop
      trigger: true
    - task: test
      file: develop/ci/test.yml

- name: promote
  plan:
    - aggregate:
      - get: develop
        trigger: true
        passed:
          - test
      - put: version
        params:
          bump: patch

    - task: bump
      file: develop/ci/bump.yml
      output_mapping:
        output: bumped

    - aggregate:
      - put: master
        params:
          repository: bumped
          tag: version/number
          tag_prefix: v

      - put: develop
        params:
          repository: bumped

