resources:
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/d/demo-version
    branch: master
    username: {{github_token}}
    file: v

- name: develop
  type: git
  source: &src
    uri: https://github.com/d/i-need-versions
    branch: develop
    username: {{github_token}}

- name: master
  type: git
  source:
    <<: *src
    branch: master

jobs:
- name: test
  plan:
    - get: develop
      trigger: true
    - task: test
      file: develop/ci/test.yml

- name: promote
  plan:
    - aggregate:
      - get: develop
        trigger: true
        passed:
          - test
      - get: master
      - get: latest_develop
        resource: develop
